---
spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev #set prod in production
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/changelog.yml
server:
  port: ${SERVER_PORT}
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        max-age: P1D
